


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_sec
    username: root
    password: 4123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: info
    org.hibernate: info

app:
    jwt-secret: JWTSecretKey
    jwt-expiration-milliseconds: 604800000